language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test

    - stage: notify_start
      script: scripts/deploy-notify-start.sh
      install: skip

    - stage: notify
      script: scripts/deploy-notify.sh
      install: skip

    - stage: deploy
      name: Application Service
      script: scripts/deploy.js application

    - stage: deploy
      name: GraphQL Service
      script: scripts/deploy.js graphql

    - stage: deploy
      name: IP Service
      script: scripts/deploy.js ip

    - stage: deploy
      name: Locale Service
      script: scripts/deploy.js locale

    - stage: deploy
      name: Mailer Service
      script: scripts/deploy.js mailer

    - stage: deploy
      name: Manage UI Service
      script: scripts/deploy.js manage

    - stage: deploy
      name: Membership Service
      script: scripts/deploy.js membership

    - stage: deploy
      name: Organization Service
      script: scripts/deploy.js organization

    - stage: deploy
      name: Token Service
      script: scripts/deploy.js token

    - stage: deploy
      name: User Service
      script: scripts/deploy.js user
