version: '3.7'

x-env-defaults: &env
  APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL-http://application}
  MAILER_SERVICE_URL: ${MAILER_SERVICE_URL-http://mailer}
  MEMBERSHIP_SERVICE_URL: ${MEMBERSHIP_SERVICE_URL-http://membership}
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017/id-me}
  NODE_ENV: development
  ORGANIZATION_SERVICE_URL: ${ORGANIZATION_SERVICE_URL-http://organization}
  TOKEN_SERVICE_URL: ${TOKEN_SERVICE_URL-http://token}
  USER_SERVICE_URL: ${USER_SERVICE_URL-http://user}
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  working_dir: /id-me
  volumes:
    - .:/id-me:cached
    - ./node_modules:/id-me/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "12000:27017"

  graphql:
    <<: *node
    working_dir: /id-me/services/graphql
    entrypoint: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12001
    depends_on:
      - application
      - membership
      - organization
      - user
    ports:
      - "12001:80"

  manage:
    <<: *node
    image: danlynn/ember-cli:3.9.0
    working_dir: /id-me/services/manage
    entrypoint: ["node_modules/.bin/ember"]
    command: ["serve", "--port", "12002", "--proxy", "http://graphql"]
    tmpfs:
      - /id-me/services/manage/tmp
    depends_on:
      - graphql
    ports:
      - "12002:12002"

  organization:
    <<: *node
    working_dir: /id-me/services/organization
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80"]
    depends_on:
      - mongodb
    ports:
      - "12003:80"

  token:
    <<: *node
    working_dir: /id-me/services/token
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80"]
    environment:
      <<: *env
      TOKEN_SECRET: ${TOKEN_SECRET-thisisntverysecret}
    depends_on:
      - mongodb
    ports:
      - "12004:80"

  mailer:
    <<: *node
    working_dir: /id-me/services/mailer
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80"]
    environment:
      <<: *env
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports:
      - "12005:80"

  user:
    <<: *node
    working_dir: /id-me/services/user
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80"]
    depends_on:
      - mongodb
      - token
      - mailer
    ports:
      - "12006:80"

  membership:
    <<: *node
    working_dir: /id-me/services/membership
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80"]
    depends_on:
      - mailer
      - mongodb
      - organization
      - token
      - user
    ports:
      - "12007:80"

  application:
    <<: *node
    working_dir: /id-me/services/application
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80"]
    depends_on:
      - mongodb
      - organization
    ports:
      - "12008:80"

volumes:
  mongodb: {}
  yarn-cache: {}
