version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  working_dir: /id-me
  volumes:
    - .:/id-me:cached
    - ./node_modules:/id-me/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "12000:27017"

  graphql:
    <<: *node
    working_dir: /id-me/services/graphql
    entrypoint: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017/id-me}
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12001
    depends_on:
      - mongodb
    ports:
      - "12001:80"

volumes:
  mongodb: {}
  yarn-cache: {}
